# FYI: Had to downgrade to Node 16 due to the following bug:
#
#        https://github.com/facebook/create-react-app/issues/11565
#
FROM node:16

RUN apt-get -y update && \
    apt-get -y install \
      git \
      less \
      vim

WORKDIR /usr/src/app

USER node
